CREATE TABLE users (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 username VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL
 );

 CREATE TABLE financial_accounts (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  balance NUMERIC NOT NULL,
  owner_user_id BIGINT REFERENCES users(id) NOT NULL
  );





